export const ConversationTypes = {
  CREATE_CONVERSATION_LOADING: "CREATE_CONVERSATION_LOADING",
  CREATE_CONVERSATION_SUCCESS: "CREATE_CONVERSATION_SUCCESS",
  CREATE_CONVERSATION_FAILURE: "CREATE_CONVERSATION_FAILURE",

  UPDATE_CONVERSATION: "UPDATE_CONVERSATION",

  LOADING_CONVERSATIONS: "LOADING_CONVERSATIONS",
  LOADING_CONVERSATIONS_SUCCESS: "LOADING_CONVERSATIONS_SUCCESS",
  LOADING_CONVERSATIONS_FAILURE: "LOADING_CONVERSATIONS_FAILURE",

  SELECT_CONVERSATION: "SELECT_CONVERSATION",
  UPDATE_SELECTED_USER: "UPDATE_SELECTED_USER",
};
